### ISSUE TITLE
Cannot subclass errors

### ISSUE THREAD

**Issue by cdignam-segment** [jshttp/http-errors#101] opened 2023-10-23 21:26 UTC
I was surprised I couldn't subclass errors. I would have expected my ValidationError class would support an `instanceof` check against itself.

```
const { BadRequest } = require('http-errors')
const assert = require('assert')


class ValidationError extends BadRequest {}

const err = new ValidationError()
console.log(err.name)
// "BadRequestError"

// err should be an instance of ValidationError
assert(err instanceof ValidationError)

```

https://runkit.com/cdignam-segment/6536e492c20c690008824a73

**Comment by jonchurch** [comment] 2024-03-08 19:17
duplicate of #98, but yes duly noted. I would expect this to work this way as well.

**Closed by jonchurch** 2024-03-08 19:17 UTC
